
export const currencies = [
  { "code": "USD", "name": "United States Dollar" },
  { "code": "EUR", "name": "Euro" },
  { "code": "JPY", "name": "Japanese Yen" },
  { "code": "GBP", "name": "British Pound Sterling" },
  { "code": "AUD", "name": "Australian Dollar" },
  { "code": "CAD", "name": "Canadian Dollar" },
  { "code": "CHF", "name": "Swiss Franc" },
  { "code": "CNY", "name": "Chinese Yuan" },
  { "code": "INR", "name": "Indian Rupee" },
  { "code": "AED", "name": "United Arab Emirates Dirham" },
  { "code": "AFN", "name": "Afghan Afghani" },
  { "code": "ALL", "name": "Albanian Lek" },
  { "code": "AMD", "name": "Armenian Dram" },
  { "code": "ANG", "name": "Netherlands Antillean Guilder" },
  { "code": "AOA", "name": "Angolan Kwanza" },
  { "code": "ARS", "name": "Argentine Peso" },
  { "code": "AWG", "name": "Aruban Florin" },
  { "code": "AZN", "name": "Azerbaijani Manat" },
  { "code": "BAM", "name": "Bosnia-Herzegovina Convertible Mark" },
  { "code": "BBD", "name": "Barbadian Dollar" },
  { "code": "BDT", "name": "Bangladeshi Taka" },
  { "code": "BGN", "name": "Bulgarian Lev" },
  { "code": "BHD", "name": "Bahraini Dinar" },
  { "code": "BIF", "name": "Burundian Franc" },
  { "code": "BMD", "name": "Bermudan Dollar" },
  { "code": "BND", "name": "Brunei Dollar" },
  { "code": "BOB", "name": "Bolivian Boliviano" },
  { "code": "BRL", "name": "Brazilian Real" },
  { "code": "BSD", "name": "Bahamian Dollar" },
  { "code": "BTN", "name": "Bhutanese Ngultrum" },
  { "code": "BWP", "name": "Botswanan Pula" },
  { "code": "BYN", "name": "Belarusian Ruble" },
  { "code": "BZD", "name": "Belize Dollar" },
  { "code": "CDF", "name": "Congolese Franc" },
  { "code": "CLP", "name": "Chilean Peso" },
  { "code": "COP", "name": "Colombian Peso" },
  { "code": "CRC", "name": "Costa Rican Colón" },
  { "code": "CUP", "name": "Cuban Peso" },
  { "code": "CVE", "name": "Cape Verdean Escudo" },
  { "code": "CZK", "name": "Czech Republic Koruna" },
  { "code": "DJF", "name": "Djiboutian Franc" },
  { "code": "DKK", "name": "Danish Krone" },
  { "code": "DOP", "name": "Dominican Peso" },
  { "code": "DZD", "name": "Algerian Dinar" },
  { "code": "EGP", "name": "Egyptian Pound" },
  { "code": "ERN", "name": "Eritrean Nakfa" },
  { "code": "ETB", "name": "Ethiopian Birr" },
  { "code": "FJD", "name": "Fijian Dollar" },
  { "code": "FKP", "name": "Falkland Islands Pound" },
  { "code": "FOK", "name": "Faroese Króna" },
  { "code": "GEL", "name": "Georgian Lari" },
  { "code": "GGP", "name": "Guernsey Pound" },
  { "code": "GHS", "name": "Ghanaian Cedi" },
  { "code": "GIP", "name": "Gibraltar Pound" },
  { "code": "GMD", "name": "Gambian Dalasi" },
  { "code": "GNF", "name": "Guinean Franc" },
  { "code": "GTQ", "name": "Guatemalan Quetzal" },
  { "code": "GYD", "name": "Guyanaese Dollar" },
  { "code": "HKD", "name": "Hong Kong Dollar" },
  { "code": "HNL", "name": "Honduran Lempira" },
  { "code": "HRK", "name": "Croatian Kuna" },
  { "code": "HTG", "name": "Haitian Gourde" },
  { "code": "HUF", "name": "Hungarian Forint" },
  { "code": "IDR", "name": "Indonesian Rupiah" },
  { "code": "ILS", "name": "Israeli New Sheqel" },
  { "code": "IMP", "name": "Manx pound" },
  { "code": "IQD", "name": "Iraqi Dinar" },
  { "code": "IRR", "name": "Iranian Rial" },
  { "code": "ISK", "name": "Icelandic Króna" },
  { "code": "JEP", "name": "Jersey Pound" },
  { "code": "JMD", "name": "Jamaican Dollar" },
  { "code": "JOD", "name": "Jordanian Dinar" },
  { "code": "KES", "name": "Kenyan Shilling" },
  { "code": "KGS", "name": "Kyrgystani Som" },
  { "code": "KHR", "name": "Cambodian Riel" },
  { "code": "KID", "name": "Kiribati Dollar" },
  { "code": "KMF", "name": "Comorian Franc" },
  { "code": "KRW", "name": "South Korean Won" },
  { "code": "KWD", "name": "Kuwaiti Dinar" },
  { "code": "KYD", "name": "Cayman Islands Dollar" },
  { "code": "KZT", "name": "Kazakhstani Tenge" },
  { "code": "LAK", "name": "Laotian Kip" },
  { "code": "LBP", "name": "Lebanese Pound" },
  { "code": "LKR", "name": "Sri Lankan Rupee" },
  { "code": "LRD", "name": "Liberian Dollar" },
  { "code": "LSL", "name": "Lesotho Loti" },
  { "code": "LYD", "name": "Libyan Dinar" },
  { "code": "MAD", "name": "Moroccan Dirham" },
  { "code": "MDL", "name": "Moldovan Leu" },
  { "code": "MGA", "name": "Malagasy Ariary" },
  { "code": "MKD", "name": "Macedonian Denar" },
  { "code": "MMK", "name": "Myanma Kyat" },
  { "code": "MNT", "name": "Mongolian Tugrik" },
  { "code": "MOP", "name": "Macanese Pataca" },
  { "code": "MRU", "name": "Mauritanian Ouguiya" },
  { "code": "MUR", "name": "Mauritian Rupee" },
  { "code": "MVR", "name": "Maldivian Rufiyaa" },
  { "code": "MWK", "name": "Malawian Kwacha" },
  { "code": "MXN", "name": "Mexican Peso" },
  { "code": "MYR", "name": "Malaysian Ringgit" },
  { "code": "MZN", "name": "Mozambican Metical" },
  { "code": "NAD", "name": "Namibian Dollar" },
  { "code": "NGN", "name": "Nigerian Naira" },
  { "code": "NIO", "name": "Nicaraguan Córdoba" },
  { "code": "NOK", "name": "Norwegian Krone" },
  { "code": "NPR", "name": "Nepalese Rupee" },
  { "code": "NZD", "name": "New Zealand Dollar" },
  { "code": "OMR", "name": "Omani Rial" },
  { "code": "PAB", "name": "Panamanian Balboa" },
  { "code": "PEN", "name": "Peruvian Nuevo Sol" },
  { "code": "PGK", "name": "Papua New Guinean Kina" },
  { "code": "PHP", "name": "Philippine Peso" },
  { "code": "PKR", "name": "Pakistani Rupee" },
  { "code": "PLN", "name": "Polish Zloty" },
  { "code": "PYG", "name": "Paraguayan Guarani" },
  { "code": "QAR", "name": "Qatari Rial" },
  { "code": "RON", "name": "Romanian Leu" },
  { "code": "RSD", "name": "Serbian Dinar" },
  { "code": "RUB", "name": "Russian Ruble" },
  { "code": "RWF", "name": "Rwandan Franc" },
  { "code": "SAR", "name": "Saudi Riyal" },
  { "code": "SBD", "name": "Solomon Islands Dollar" },
  { "code": "SCR", "name": "Seychellois Rupee" },
  { "code": "SDG", "name": "Sudanese Pound" },
  { "code": "SEK", "name": "Swedish Krona" },
  { "code": "SGD", "name": "Singapore Dollar" },
  { "code": "SHP", "name": "Saint Helena Pound" },
  { "code": "SLL", "name": "Sierra Leonean Leone" },
  { "code": "SOS", "name": "Somali Shilling" },
  { "code": "SRD", "name": "Surinamese Dollar" },
  { "code": "SSP", "name": "South Sudanese Pound" },
  { "code": "STN", "name": "São Tomé and Príncipe Dobra" },
  { "code": "SYP", "name": "Syrian Pound" },
  { "code": "SZL", "name": "Swazi Lilangeni" },
  { "code": "THB", "name": "Thai Baht" },
  { "code": "TJS", "name": "Tajikistani Somoni" },
  { "code": "TMT", "name": "Turkmenistani Manat" },
  { "code": "TND", "name": "Tunisian Dinar" },
  { "code": "TOP", "name": "Tongan Pa'anga" },
  { "code": "TRY", "name": "Turkish Lira" },
  { "code": "TTD", "name": "Trinidad and Tobago Dollar" },
  { "code": "TVD", "name": "Tuvaluan Dollar" },
  { "code": "TWD", "name": "New Taiwan Dollar" },
  { "code": "TZS", "name": "Tanzanian Shilling" },
  { "code": "UAH", "name": "Ukrainian Hryvnia" },
  { "code": "UGX", "name": "Ugandan Shilling" },
  { "code": "UYU", "name": "Uruguayan Peso" },
  { "code": "UZS", "name": "Uzbekistan Som" },
  { "code": "VES", "name": "Venezuelan Bolívar Soberano" },
  { "code": "VND", "name": "Vietnamese Dong" },
  { "code": "VUV", "name": "Vanuatu Vatu" },
  { "code": "WST", "name": "Samoan Tala" },
  { "code": "XAF", "name": "CFA Franc BEAC" },
  { "code": "XCD", "name": "East Caribbean Dollar" },
  { "code": "XDR", "name": "Special Drawing Rights" },
  { "code": "XOF", "name": "CFA Franc BCEAO" },
  { "code": "XPF", "name": "CFP Franc" },
  { "code": "YER", "name": "Yemeni Rial" },
  { "code": "ZAR", "name": "South African Rand" },
  { "code": "ZMW", "name": "Zambian Kwacha" },
  { "code": "ZWL", "name": "Zimbabwean Dollar" },
  { "code": "BTC", "name": "Bitcoin (Crypto)" },
  { "code": "ETH", "name": "Ethereum (Crypto)" },
  { "code": "USDT", "name": "Tether (Crypto)" },
  { "code": "BNB", "name": "Binance Coin (Crypto)" },
  { "code": "XRP", "name": "Ripple (Crypto)" },
  { "code": "LTC", "name": "Litecoin (Crypto)" },
  { "code": "DOGE", "name": "Dogecoin (Crypto)" },
  { "code": "SOL", "name": "Solana (Crypto)" },
  { "code": "ADA", "name": "Cardano (Crypto)" },
  { "code": "TRX", "name": "TRON (Crypto)" },
  { "code": "LINK", "name": "Chainlink (Crypto)" },
  { "code": "MATIC", "name": "Polygon (Crypto)" },
  { "code": "DOT", "name": "Polkadot (Crypto)" },
  { "code": "SHIB", "name": "Shiba Inu (Crypto)" },
  { "code": "AVAX", "name": "Avalanche (Crypto)" },
  { "code": "DAI", "name": "Dai (Crypto)" },
  { "code": "WBTC", "name": "Wrapped Bitcoin (Crypto)" },
  { "code": "BCH", "name": "Bitcoin Cash (Crypto)" },
  { "code": "UNI", "name": "Uniswap (Crypto)" },
  { "code": "XLM", "name": "Stellar (Crypto)" },
  { "code": "LEO", "name": "UNUS SED LEO (Crypto)" },
  { "code": "ETC", "name": "Ethereum Classic (Crypto)" },
  { "code": "XMR", "name": "Monero (Crypto)" },
  { "code": "OKB", "name": "OKB (Crypto)" },
  { "code": "ATOM", "name": "Cosmos (Crypto)" },
  { "code": "ICP", "name": "Internet Computer (Crypto)" },
  { "code": "FIL", "name": "Filecoin (Crypto)" },
  { "code": "HBAR", "name": "Hedera (Crypto)" },
  { "code": "APT", "name": "Aptos (Crypto)" },
  { "code": "LDO", "name": "Lido DAO (Crypto)" },
  { "code": "CRO", "name": "Cronos (Crypto)" },
  { "code": "NEAR", "name": "Near Protocol (Crypto)" },
  { "code": "VET", "name": "VeChain (Crypto)" },
  { "code": "QNT", "name": "Quant (Crypto)" },
  { "code": "ARB", "name": "Arbitrum (Crypto)" },
  { "code": "ALGO", "name": "Algorand (Crypto)" },
  { "code": "GRT", "name": "The Graph (Crypto)" },
  { "code": "OP", "name": "Optimism (Crypto)" },
  { "code": "EOS", "name": "EOS (Crypto)" },
  { "code": "SAND", "name": "The Sandbox (Crypto)" },
  { "code": "MANA", "name": "Decentraland (Crypto)" },
  { "code": "EGLD", "name": "MultiversX (Crypto)" },
  { "code": "XTZ", "name": "Tezos (Crypto)" },
  { "code": "AAVE", "name": "Aave (Crypto)" },
  { "code": "THETA", "name": "Theta Network (Crypto)" },
  { "code": "STX", "name": "Stacks (Crypto)" },
  { "code": "IMX", "name": "Immutable (Crypto)" },
  { "code": "MINA", "name": "Mina (Crypto)" },
  { "code": "BSV", "name": "Bitcoin SV (Crypto)" },
  { "code": "RNDR", "name": "Render Token (Crypto)" },
  { "code": "INJ", "name": "Injective (Crypto)" },
  { "code": "SUI", "name": "Sui (Crypto)" },
  { "code": "MKR", "name": "Maker (Crypto)" },
  { "code": "KCS", "name": "KuCoin Token (Crypto)" },
  { "code": "XEC", "name": "eCash (Crypto)" },
  { "code": "ZEC", "name": "Zcash (Crypto)" },
  { "code": "IOTA", "name": "IOTA (Crypto)" },
  { "code": "BTT", "name": "BitTorrent (Crypto)" },
  { "code": "RPL", "name": "Rocket Pool (Crypto)" },
  { "code": "HT", "name": "Huobi Token (Crypto)" },
  { "code": "TUSD", "name": "TrueUSD (Crypto)" },
  { "code": "GMX", "name": "GMX (Crypto)" },
  { "code": "CRV", "name": "Curve DAO Token (Crypto)" },
  { "code": "PEPE", "name": "Pepe (Crypto)" },
  { "code": "NEO", "name": "Neo (Crypto)" },
  { "code": "DASH", "name": "Dash (Crypto)" },
  { "code": "KAVA", "name": "Kava (Crypto)" },
  { "code": "CAKE", "name": "PancakeSwap (Crypto)" },
  { "code": "SNX", "name": "Synthetix (Crypto)" },
  { "code": "USDP", "name": "Pax Dollar (Crypto)" },
  { "code": "PAXG", "name": "PAX Gold (Crypto)" },
  { "code": "FLOW", "name": "Flow (Crypto)" },
  { "code": "WEMIX", "name": "WEMIX (Crypto)" },
  { "code": "KLAY", "name": "Klaytn (Crypto)" },
  { "code": "TWT", "name": "Trust Wallet Token (Crypto)" },
  { "code": "CHZ", "name": "Chiliz (Crypto)" },
  { "code": "ZIL", "name": "Zilliqa (Crypto)" },
  { "code": "CFX", "name": "Conflux (Crypto)" },
  { "code": "GALA", "name": "Gala (Crypto)" },
  { "code": "FET", "name": "Fetch.ai (Crypto)" },
  { "code": "COMP", "name": "Compound (Crypto)" },
  { "code": "BAT", "name": "Basic Attention Token (Crypto)" },
  { "code": "NEXO", "name": "Nexo (Crypto)" },
  { "code": "ENJ", "name": "Enjin Coin (Crypto)" },
  { "code": "WAVES", "name": "Waves (Crypto)" },
  { "code": "LRC", "name": "Loopring (Crypto)" },
  { "code": "ROSE", "name": "Oasis Network (Crypto)" },
  { "code": "FLOKI", "name": "FLOKI (Crypto)" },
  { "code": "DYDX", "name": "dYdX (Crypto)" },
  { "code": "AGIX", "name": "SingularityNET (Crypto)" },
  { "code": "CVX", "name": "Convex Finance (Crypto)" },
  { "code": "OSMO", "name": "Osmosis (Crypto)" },
  { "code": "SUSHI", "name": "SushiSwap (Crypto)" },
  { "code": "QTUM", "name": "Qtum (Crypto)" },
  { "code": "1INCH", "name": "1inch Network (Crypto)" },
  { "code": "HOT", "name": "Holo (Crypto)" },
  { "code": "BABYDOGE", "name": "Baby Doge Coin (Crypto)" },
  { "code": "MASK", "name": "Mask Network (Crypto)" },
  { "code": "ANKR", "name": "Ankr (Crypto)" },
  { "code": "AXS", "name": "Axie Infinity (Crypto)" },
  { "code": "WOO", "name": "WOO Network (Crypto)" },
  { "code": "AUDIO", "name": "Audius (Crypto)" },
  { "code": "BAL", "name": "Balancer (Crypto)" },
  { "code": "CELO", "name": "Celo (Crypto)" },
  { "code": "BAND", "name": "Band Protocol (Crypto)" },
  { "code": "CHSB", "name": "SwissBorg (Crypto)" },
  { "code": "AR", "name": "Arweave (Crypto)" },
  { "code": "RVN", "name": "Ravencoin (Crypto)" },
  { "code": "SC", "name": "Siacoin (Crypto)" },
  { "code": "DCR", "name": "Decred (Crypto)" },
  { "code": "HNT", "name": "Helium (Crypto)" },
  { "code": "ONT", "name": "Ontology (Crypto)" },
  { "code": "YFI", "name": "yearn.finance (Crypto)" },
  { "code": "UMA", "name": "UMA (Crypto)" },
  { "code": "KSM", "name": "Kusama (Crypto)" },
  { "code": "SXP", "name": "Solar (Crypto)" },
  { "code": "REN", "name": "Ren (Crypto)" },
  { "code": "IOST", "name": "IOST (Crypto)" },
  { "code": "KDA", "name": "Kadena (Crypto)" },
  { "code": "GLMR", "name": "Moonbeam (Crypto)" },
  { "code": "ONE", "name": "Harmony (Crypto)" },
  { "code": "ICX", "name": "ICON (Crypto)" },
  { "code": "STORJ", "name": "Storj (Crypto)" },
  { "code": "OMG", "name": "OMG Network (Crypto)" },
  { "code": "API3", "name": "API3 (Crypto)" },
  { "code": "OGN", "name": "Origin Protocol (Crypto)" },
  { "code": "FLR", "name": "Flare (Crypto)" },
  { "code": "JASMY", "name": "JasmyCoin (Crypto)" },
  { "code": "BLUR", "name": "Blur (Crypto)" },
  { "code": "IOTX", "name": "IoTeX (Crypto)" },
  { "code": "OCEAN", "name": "Ocean Protocol (Crypto)" },
  { "code": "BNX", "name": "BinaryX (Crypto)" },
  { "code": "POWR", "name": "Powerledger (Crypto)" },
  { "code": "PYR", "name": "Vulcan Forged (Crypto)" },
  { "code": "SPELL", "name": "Spell Token (Crypto)" },
  { "code": "ENS", "name": "Ethereum Name Service (Crypto)" },
  { "code": "VGX", "name": "Voyager Token (Crypto)" },
  { "code": "REQ", "name": "Request (Crypto)" },
  { "code": "SKL", "name": "SKALE Network (Crypto)" },
  { "code": "RLC", "name": "iExec RLC (Crypto)" },
  { "code": "COTI", "name": "COTI (Crypto)" },
  { "code": "FXS", "name": "Frax Share (Crypto)" },
  { "code": "JOE", "name": "JOE (Crypto)" },
  { "code": "ALPHA", "name": "Stella (Crypto)" },
  { "code": "ASTR", "name": "Astar (Crypto)" },
  { "code": "BICO", "name": "Biconomy (Crypto)" },
  { "code": "IDEX", "name": "IDEX (Crypto)" },
  { "code": "OXT", "name": "Orchid (Crypto)" },
  { "code": "PERP", "name": "Perpetual Protocol (Crypto)" },
  { "code": "RSR", "name": "Reserve Rights (Crypto)" },
  { "code": "TRU", "name": "TrueFi (Crypto)" },
  { "code": "USTC", "name": "TerraClassicUSD (Crypto)" },
  { "code": "GNS", "name": "Gains Network (Crypto)" },
  { "code": "PLA", "name": "PlayDapp (Crypto)" },
  { "code": "SYS", "name": "Syscoin (Crypto)" },
  { "code": "MAGIC", "name": "MAGIC (Crypto)" },
  { "code": "BADGER", "name": "Badger DAO (Crypto)" },
  { "code": "CTSI", "name": "Cartesi (Crypto)" },
  { "code": "ILV", "name": "Illuvium (Crypto)" },
  { "code": "MOB", "name": "MobileCoin (Crypto)" },
  { "code": "NKN", "name": "NKN (Crypto)" },
  { "code": "STG", "name": "Stargate Finance (Crypto)" },
  { "code": "AMP", "name": "Amp (Crypto)" },
  { "code": "BLZ", "name": "Bluzelle (Crypto)" },
  { "code": "CVC", "name": "Civic (Crypto)" },
  { "code": "EFI", "name": "Efinity Token (Crypto)" },
  { "code": "FUN", "name": "FUNToken (Crypto)" },
  { "code": "GHST", "name": "Aavegotchi (Crypto)" },
  { "code": "HFT", "name": "Hashflow (Crypto)" },
  { "code": "ID", "name": "SPACE ID (Crypto)" },
  { "code": "MDT", "name": "Measurable Data Token (Crypto)" },
  { "code": "PRO", "name": "Propy (Crypto)" },
  { "code": "RAD", "name": "Radicle (Crypto)" },
  { "code": "SNT", "name": "Status (Crypto)" },
  { "code": "TRIBE", "name": "Tribe (Crypto)" },
  { "code": "VTHO", "name": "VeThor Token (Crypto)" },
  { "code": "XNO", "name": "Nano (Crypto)" },
  { "code": "ZEN", "name": "Horizen (Crypto)" },
  { "code": "ACH", "name": "Alchemy Pay (Crypto)" },
  { "code": "ALI", "name": "Artificial Liquid Intelligence (Crypto)" },
  { "code": "ARPA", "name": "ARPA Chain (Crypto)" },
  { "code": "AURORA", "name": "Aurora (Crypto)" },
  { "code": "BOND", "name": "BarnBridge (Crypto)" },
  { "code": "CEEK", "name": "CEEK VR (Crypto)" },
  { "code": "COS", "name": "Contentos (Crypto)" },
  { "code": "DENT", "name": "Dent (Crypto)" },
  { "code": "DGB", "name": "DigiByte (Crypto)" },
  { "code": "DODO", "name": "DODO (Crypto)" },
  { "code": "EDU", "name": "Open Campus (Crypto)" },
  { "code": "ELF", "name": "aelf (Crypto)" },
  { "code": "FLUX", "name": "Flux (Crypto)" },
  { "code": "FORTH", "name": "Ampleforth Governance Token (Crypto)" },
  { "code": "GFT", "name": "Gifto (Crypto)" },
  { "code": "GLM", "name": "Golem (Crypto)" },
  { "code": "HIGH", "name": "Highstreet (Crypto)" },
  { "code": "HOOK", "name": "Hooked Protocol (Crypto)" },
  { "code": "IQ", "name": "IQ.wiki (Crypto)" },
  { "code": "KEY", "name": "SelfKey (Crypto)" },
  { "code": "LINA", "name": "Linear (Crypto)" },
  { "code": "LPT", "name": "Livepeer (Crypto)" },
  { "code": "LQTY", "name": "Liquity (Crypto)" },
  { "code": "MDX", "name": "Mdex (Crypto)" },
  { "code": "MFT", "name": "Hifi Finance (Crypto)" },
  { "code": "MTL", "name": "Metal DAO (Crypto)" },
  { "code": "NMR", "name": "Numeraire (Crypto)" },
  { "code": "NU", "name": "NuCypher (Crypto)" },
  { "code": "OAX", "name": "OAX (Crypto)" },
  { "code": "ONG", "name": "Ontology Gas (Crypto)" },
  { "code": "ORN", "name": "Orion Protocol (Crypto)" },
  { "code": "PHA", "name": "Phala Network (Crypto)" },
  { "code": "POLS", "name": "Polkastarter (Crypto)" },
  { "code": "POND", "name": "Marlin (Crypto)" },
  { "code": "QUICK", "name": "QuickSwap (Crypto)" },
  { "code": "RARE", "name": "SuperRare (Crypto)" },
  { "code": "REEF", "name": "Reef (Crypto)" },
  { "code": "RIF", "name": "RSK Infrastructure Framework (Crypto)" },
  { "code": "RLY", "name": "Rally (Crypto)" },
  { "code": "RUNE", "name": "THORChain (Crypto)" },
  { "code": "SLP", "name": "Smooth Love Potion (Crypto)" },
  { "code": "SSV", "name": "ssv.network (Crypto)" },
  { "code": "STEEM", "name": "Steem (Crypto)" },
  { "code": "STRAX", "name": "Stratis (Crypto)" },
  { "code": "SUPER", "name": "SuperVerse (Crypto)" },
  { "code": "SYN", "name": "Synapse (Crypto)" },
  { "code": "T", "name": "Threshold (Crypto)" },
  { "code": "TFUEL", "name": "Theta Fuel (Crypto)" },
  { "code": "TLM", "name": "Alien Worlds (Crypto)" },
  { "code": "TRB", "name": "Tellor (Crypto)" },
  { "code": "TVK", "name": "Virtua (Crypto)" },
  { "code": "UFT", "name": "UniLend (Crypto)" },
  { "code": "UTK", "name": "xMoney (Crypto)" },
  { "code": "VRA", "name": "Verasity (Crypto)" },
  { "code": "WIN", "name": "WINkLink (Crypto)" },
  { "code": "WRX", "name": "WazirX (Crypto)" },
  { "code": "WTC", "name": "Waltonchain (Crypto)" },
  { "code": "XVS", "name": "Venus (Crypto)" },
  { "code": "YGG", "name": "Yield Guild Games (Crypto)" },
  { "code": "ADX", "name": "AdEx (Crypto)" },
  { "code": "AERGO", "name": "Aergo (Crypto)" },
  { "code": "AKRO", "name": "Akropolis (Crypto)" },
  { "code": "ALCX", "name": "Alchemix (Crypto)" },
  { "code": "AMB", "name": "AirDAO (Crypto)" },
  { "code": "ANT", "name": "Aragon (Crypto)" },
  { "code": "APE", "name": "ApeCoin (Crypto)" },
  { "code": "AST", "name": "AirSwap (Crypto)" },
  { "code": "AUCTION", "name": "Bounce Token (Crypto)" },
  { "code": "BADGER", "name": "Badger DAO (Crypto)" },
  { "code": "BAKE", "name": "BakeryToken (Crypto)" },
  { "code": "BEL", "name": "Bella Protocol (Crypto)" },
  { "code": "BETA", "name": "Beta Finance (Crypto)" },
  { "code": "BNT", "name": "Bancor (Crypto)" },
  { "code": "BURGER", "name": "BurgerCities (Crypto)" },
  { "code": "C98", "name": "Coin98 (Crypto)" },
  { "code": "CELR", "name": "Celer Network (Crypto)" },
  { "code": "CHR", "name": "Chromia (Crypto)" },
  { "code": "CKB", "name": "Nervos Network (Crypto)" },
  { "code": "CLV", "name": "CLV (Crypto)" },
  { "code": "COMBO", "name": "COMBO (Crypto)" },
  { "code": "COVAL", "name": "Circuits of Value (Crypto)" },
  { "code": "CTK", "name": "Shentu (Crypto)" },
  { "code": "CTX", "name": "Cortex (Crypto)" },
  { "code": "DAR", "name": "Mines of Dalarnia (Crypto)" },
  { "code": "DATA", "name": "Streamr (Crypto)" },
  { "code": "DEGO", "name": "Dego Finance (Crypto)" },
  { "code": "DIA", "name": "DIA (Crypto)" },
  { "code": "DEXE", "name": "DeXe (Crypto)" },
  { "code": "DUSK", "name": "Dusk (Crypto)" },
  { "code": "ERN", "name": "Ethernity Chain (Crypto)" },
  { "code": "FARM", "name": "Harvest Finance (Crypto)" },
  { "code": "FIS", "name": "Stafi (Crypto)" },
  { "code": "FIO", "name": "FIO Protocol (Crypto)" },
  { "code": "FIRO", "name": "Firo (Crypto)" },
  { "code": "FOR", "name": "ForTube (Crypto)" },
  { "code": "FRONT", "name": "Frontier (Crypto)" },
  { "code": "FX", "name": "Function X (Crypto)" },
  { "code": "GAL", "name": "Galxe (Crypto)" },
  { "code": "GTC", "name": "Gitcoin (Crypto)" },
  { "code": "HARD", "name": "Kava Lend (Crypto)" },
  { "code": "HIVE", "name": "Hive (Crypto)" },
  { "code": "IDEX", "name": "IDEX (Crypto)" },
  { "code": "IRIS", "name": "IRISnet (Crypto)" },
  { "code": "JUV", "name": "Juventus Fan Token (Crypto)" },
  { "code": "KEEP", "name": "Keep Network (Crypto)" },
  { "code": "KNC", "name": "Kyber Network Crystal v2 (Crypto)" },
  { "code": "KP3R", "name": "Keep3rV1 (Crypto)" },
  { "code": "LAZIO", "name": "Lazio Fan Token (Crypto)" },
  { "code": "LIT", "name": "Litentry (Crypto)" },
  { "code": "LOKA", "name": "League of Kingdoms (Crypto)" },
  { "code": "LOOM", "name": "Loom Network (Crypto)" },
  { "code": "LSK", "name": "Lisk (Crypto)" },
  { "code": "MBL", "name": "MovieBloc (Crypto)" },
  { "code": "MC", "name": "Merit Circle (Crypto)" },
  { "code": "MITH", "name": "Mithril (Crypto)" },
  { "code": "MLN", "name": "Enzyme (Crypto)" },
  { "code": "MOVR", "name": "Moonriver (Crypto)" },
  { "code": "MULTI", "name": "Multichain (Crypto)" },
  { "code": "NULS", "name": "NULS (Crypto)" },
  { "code": "OOKI", "name": "Ooki Protocol (Crypto)" },
  { "code": "ORN", "name": "Orion Protocol (Crypto)" },
  { "code": "PEOPLE", "name": "ConstitutionDAO (Crypto)" },
  { "code": "PERL", "name": "PERL.eco (Crypto)" },
  { "code": "PNT", "name": "pNetwork (Crypto)" },
  { "code": "POLYX", "name": "Polymesh (Crypto)" },
  { "code": "PORTO", "name": "FC Porto Fan Token (Crypto)" },
  { "code": "PROS", "name": "Prosper (Crypto)" },
  { "code": "PSG", "name": "Paris Saint-Germain Fan Token (Crypto)" },
  { "code": "PUNDIX", "name": "Pundi X (Crypto)" },
  { "code": "QI", "name": "BENQI (Crypto)" },
  { "code": "QKC", "name": "QuarkChain (Crypto)" },
  { "code": "RARE", "name": "SuperRare (Crypto)" },
  { "code": "RAY", "name": "Raydium (Crypto)" },
  { "code": "REI", "name": "REI Network (Crypto)" },
  { "code": "REP", "name": "Augur (Crypto)" },
  { "code": "REQ", "name": "Request (Crypto)" },
  { "code": "SAND", "name": "The Sandbox (Crypto)" },
  { "code": "SANTOS", "name": "Santos FC Fan Token (Crypto)" },
  { "code": "SCRT", "name": "Secret (Crypto)" },
  { "code": "SFP", "name": "SafePal (Crypto)" },
  { "code": "STMX", "name": "StormX (Crypto)" },
  { "code": "STPT", "name": "STP (Crypto)" },
  { "code": "SUN", "name": "Sun (Crypto)" },
  { "code": "TKO", "name": "Toko Token (Crypto)" },
  { "code": "TLM", "name": "Alien Worlds (Crypto)" },
  { "code": "TOMO", "name": "Viction (Crypto)" },
  { "code": "TRU", "name": "TrueFi (Crypto)" },
  { "code": "UNFI", "name": "Unifi Protocol DAO (Crypto)" },
  { "code": "VIB", "name": "Viberate (Crypto)" },
  { "code": "VIDT", "name": "VIDT DAO (Crypto)" },
  { "code": "VITE", "name": "Vite (Crypto)" },
  { "code": "VOXEL", "name": "Voxies (Crypto)" },
  { "code": "WAN", "name": "Wanchain (Crypto)" },
  { "code": "WAXP", "name": "WAX (Crypto)" },
  { "code": "WING", "name": "Wing Finance (Crypto)" },
  { "code": "WNXM", "name": "Wrapped NXM (Crypto)" },
  { "code": "XEM", "name": "NEM (Crypto)" },
  { "code": "XVG", "name": "Verge (Crypto)" },
  { "code": "YFII", "name": "DFI.money (Crypto)" },
  { "code": "ZRX", "name": "0x (Crypto)" }
]
