
export default function PrivacyPolicyPage() {
    return (
        <div>
            <h1 className="text-3xl font-bold text-center">Privacy Policy for UniversalPay</h1>
            <p><strong>Last updated:</strong> {new Date().toLocaleDateString()}</p>
            
            <h2>1. Introduction</h2>
            <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
            <p>We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.</p>

            <h2>2. Interpretation and Definitions</h2>
            <h3>Interpretation</h3>
            <p>Words with capitalized initial letters have defined meanings. These definitions apply regardless of whether they appear in singular or plural form.</p>
            <h3>Definitions</h3>
            <ul>
                <li><strong>"Company"</strong> (referred to as "We", "Us", or "Our") refers to UniversalPay.</li>
                <li><strong>"Service"</strong> refers to the UniversalPay website, APIs, and related services.</li>
                <li><strong>"You"</strong> means the individual or legal entity using our Service.</li>
                <li><strong>"Personal Data"</strong> is any information that relates to an identified or identifiable individual.</li>
                <li><strong>"Usage Data"</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
            </ul>

            <h2>3. Collecting and Using Your Personal Data</h2>
            <h3>Types of Data Collected</h3>
            
            <h4>Personal Data</h4>
            <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. This may include, but is not limited to:</p>
            <ul>
                <li>Email address</li>
                <li>First name and last name</li>
                <li>Phone number</li>
                <li>Business Name and Address</li>
                <li>Transaction Data</li>
                <li>Usage Data</li>
            </ul>
            
            <h4>Usage Data</h4>
            <p>Usage Data is collected automatically when using the Service.</p>
            <p>Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
            
            <h2>4. Use of Your Personal Data</h2>
            <p>The Company may use Personal Data for the following purposes:</p>
            <ul>
                <li><strong>To provide and maintain our Service,</strong> including to monitor the usage of our Service.</li>
                <li><strong>To manage Your Account:</strong> to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</li>
                <li><strong>For the performance of a contract:</strong> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</li>
                <li><strong>To contact You:</strong> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</li>
                <li><strong>To manage Your requests:</strong> To attend and manage Your requests to Us.</li>
                <li><strong>For business transfers:</strong> We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets.</li>
            </ul>

            <h2>5. Retention of Your Personal Data</h2>
            <p>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>

            <h2>6. Security of Your Personal Data</h2>
            <p>The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>
            
            <h2>7. Contact Us</h2>
            <p>If you have any questions about this Privacy Policy, You can contact us:</p>
            <ul>
                <li>By visiting our support page: [Link to Support Page]</li>
            </ul>
        </div>
    )
}
