const PrivacyPolicy = () => {
    return (
      <div className="flex justify-center">
        <div className="p-6 max-w-4xl text-gray-800">
          <h1 className="text-3xl font-bold mb-4 text-center">Privacy Policy for UniversalPay</h1>
          <p className="text-sm text-gray-500 mb-6 text-center">Last updated: 8/7/2025</p>
  
          <section className="mb-6">
            <h2 className="text-2xl font-semibold mb-2">1. Introduction</h2>
            <p>
              This Privacy Policy describes Our policies and procedures on the collection, use, and disclosure of Your information when You use the Service, and informs You about Your privacy rights and how the law protects You.
            </p>
            <p>
              We use Your Personal Data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
            </p>
          </section>
  
          <section className="mb-6">
            <h2 className="text-2xl font-semibold mb-2">2. Interpretation and Definitions</h2>
  
            <h3 className="text-xl font-semibold mt-4">2.1 Interpretation</h3>
            <p>
              Words with capitalized initial letters have defined meanings. These definitions apply regardless of whether they appear in singular or plural form.
            </p>
  
            <h3 className="text-xl font-semibold mt-4">2.2 Definitions</h3>
            <ul className="list-disc list-inside">
              <li><strong>Company</strong>: Refers to UniversalPay ("We", "Us", or "Our").</li>
              <li><strong>Service</strong>: Refers to the UniversalPay website, APIs, and related services.</li>
              <li><strong>You</strong>: The individual or legal entity using our Service.</li>
              <li><strong>Personal Data</strong>: Any information that relates to an identified or identifiable individual.</li>
              <li><strong>Usage Data</strong>: Data collected automatically, either generated by use of the Service or from the Service infrastructure itself.</li>
            </ul>
          </section>
  
          <section className="mb-6">
            <h2 className="text-2xl font-semibold mb-2">3. Collecting and Using Your Personal Data</h2>
  
            <h3 className="text-xl font-semibold mt-4">3.1 Personal Data</h3>
            <p>
              While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. This may include, but is not limited to:
            </p>
            <ul className="list-disc list-inside">
              <li>Email address</li>
              <li>First name and last name</li>
              <li>Phone number</li>
              <li>Business name and address</li>
              <li>Transaction details</li>
            </ul>
  
            <h3 className="text-xl font-semibold mt-4">3.2 Usage Data</h3>
            <p>
              Usage Data is collected automatically when using the Service. It may include:
            </p>
            <ul className="list-disc list-inside">
              <li>Your device's IP address</li>
              <li>Browser type and version</li>
              <li>Pages visited and time spent</li>
              <li>Date and time of visits</li>
              <li>Unique device identifiers</li>
              <li>Other diagnostic data</li>
            </ul>
          </section>
  
          <section className="mb-6">
            <h2 className="text-2xl font-semibold mb-2">4. Use of Your Personal Data</h2>
            <p>The Company may use Personal Data for the following purposes:</p>
            <ul className="list-disc list-inside">
              <li>To provide and maintain our Service, including monitoring usage.</li>
              <li>To manage Your Account as a registered user.</li>
              <li>For contract performance regarding purchases or other agreements.</li>
              <li>To contact You with updates, security alerts, or service-related messages.</li>
              <li>To respond to and manage Your requests to Us.</li>
              <li>For business transfers such as mergers or restructuring.</li>
            </ul>
          </section>
  
          <section className="mb-6">
            <h2 className="text-2xl font-semibold mb-2">5. Retention of Your Personal Data</h2>
            <p>
              We retain Your Personal Data only as long as necessary for the purposes outlined in this Privacy Policy. We may retain and use Your data to comply with legal obligations, resolve disputes, and enforce our agreements.
            </p>
          </section>
  
          <section className="mb-6">
            <h2 className="text-2xl font-semibold mb-2">6. Security of Your Personal Data</h2>
            <p>
              The security of Your Personal Data is important to Us. We implement administrative, technical, and physical safeguards designed to protect Your information. However, no method of transmission over the Internet or method of electronic storage is 100% secure, and We cannot guarantee absolute security.
            </p>
          </section>
  
          <section>
            <h2 className="text-2xl font-semibold mb-2">7. Contact Us</h2>
            <p>
              If you have any questions about this Privacy Policy, You can contact us:
            </p>
            <p>
              By visiting our support page: <a href="https://universalpay.com/support" className="text-blue-600 underline">https://universalpay.com/support</a>
            </p>
          </section>
        </div>
      </div>
    );
  };
  
  export default PrivacyPolicy;
  